version: 2.1
jobs:
  build:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/teamhub
    steps:
      - checkout
      - run:
          name: Start containerdocker-compose
          command: |
            docker-compose up -d

